apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: release-binary
          resources: {}
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/build-scan-push/build-scan-push.yaml@versionStream
          name: build-container
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/build-scan-push/build-scan-push.yaml@versionStream
          name: push-container
        - name: chart-docs
          resources: {}
        - image: ghcr.io/jenkins-x/jx-boot:3.10.73
          name: set-github-action-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            sed -i -e "s/jx-release-version:[0-9\.]*/jx-release-version:$VERSION/" action.yml
        - name: changelog
          resources: {}
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/supply-chain-security/task.yaml@versionStream
          name: download-syft
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/supply-chain-security/task.yaml@versionStream
          name: build-and-push-sbom
          resources: {}
        - name: cleanup-image-tar
          image: alpine:3.16
          resources: {}
          script: |
            #!/bin/sh
            rm -f /workspace/source/image.tar
        - name: upload-binaries
          resources: {}
        - name: promote-release
          resources: {}
        - image: ghcr.io/jenkins-x/jx-boot:3.10.73
          name: promote-action
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            git clone https://github.com/jenkins-x-plugins/$REPO_NAME update-action
            cd update-action
            sed -i -e "s|ghcr.io/jenkins-x/$REPO_NAME:.*|ghcr.io/jenkins-x/$REPO_NAME:$VERSION'|" action.yml
            sed -i -e "s|ghcr.io/jenkins-x/$REPO_NAME:.*|ghcr.io/jenkins-x/$REPO_NAME:$VERSION|" README.md
            sed -i -e "s|jenkins-x-plugins/$REPO_NAME@v.*|jenkins-x-plugins/$REPO_NAME@v$VERSION|g" README.md

            git add * || true
            git commit -a -m "chore: upgrade image to $VERSION" --allow-empty
            git push
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
